# Generated by Django 4.1.7 on 2023-04-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30, null=True)),
                ('ccity', models.CharField(max_length=30, null=True)),
                ('cstate', models.CharField(max_length=30, null=True)),
                ('czip', models.CharField(max_length=30, null=True)),
                ('ccost', models.CharField(max_length=30, null=True)),
                ('cdis', models.CharField(max_length=300, null=True)),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
