# Generated by Django 4.1.7 on 2023-03-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('passw', models.CharField(max_length=30)),
                ('wpm', models.IntegerField()),
                ('cpm', models.IntegerField()),
                ('accu', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('errors', models.IntegerField()),
            ],
        ),
    ]
