# Generated by Django 4.1.7 on 2023-03-31 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_user_accu_alter_user_cpm_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rank',
            new_name='score',
        ),
    ]
